### ISSUE TITLE
Invali literal for int

### ISSUE THREAD

**Issue by AlexDesign-Fr** [w-e-w/stable-diffusion-webui-GPU-temperature-protection#2] opened 2023-08-12 17:37 UTC
I've got and error message  display in the dos command line.
The error is :
`Error GPU temperature protection]: invalid literal for int() with base 10: '84\r\n45'`

I guess there is a type convertion error in the script...
I don't know if that help, but my graphic board is an Nvidia Geforce GTX 1080

**Comment by w-e-w** [comment] 2023-08-12 18:06
do you have multiple gpus?

**Comment by AlexDesign-Fr** [comment] 2023-08-12 18:51
Yes :
- Nvidia Geforce GTX 1080
- Nvidia Geforce GTX 650

**Comment by w-e-w** [comment] 2023-08-12 19:53
should support multi GPU now

**Comment by AlexDesign-Fr** [comment] 2023-08-13 00:23
Unfornatly, after upgrading the extension, th Web UI crash.

**Comment by w-e-w** [comment] 2023-08-13 02:25
error logs

**Comment by w-e-w** [comment] 2023-08-13 02:33
after inspection it should not be possible for what I have changed to cause a crash
whatever is causing the crash is likely not caused by me
the worst that can happen is as before it's not able to read the temperature correctly

**Comment by w-e-w** [comment] 2023-08-13 10:26
found the cause. should be fixed now

in dev brunch we have already switched to gradio 3.39.0
but in webui1.5.1 we are still using 3.32.0
I've used some new parameters that are only existing 3.39.0, so when you load it up in webui 1.5.1 it crashed

**Closed as completed by w-e-w** 2023-08-13 10:26 UTC
